version: "3.6"

services:

  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./api:/var/www/api:cached
      - ./configs/nginx:/etc/nginx/conf.d:cached
      - ./logs/nginx:/var/log/nginx:cached
      - /etc/ssl:/etc/ssl
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot

  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/api

  nodejs:
    build:
      context: ./nuxt/
      dockerfile: ./nuxt/Dockerfile
    ports:
      - "3000:3000"

  mardiadb:
    image: mariadb:10.5
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_USER_PASSWORD}
    volumes:
      - ./databases/mariadb:/var/lib/mysql